// SPDX-License-Identifier: Apache-2.0

// Measures how wide each character is in the styles the title of an opened
// node's box is set in, with the fonts Codemap ships, and writes the table
// the layout reads to keep a box as wide as its title. Run it again when a
// font or one of these styles changes:
//
//   node scripts/text-widths.mjs

import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { chromium } from "@playwright/test";

const fonts = new URL("../packages/web/src/design/fonts/fonts.css", import.meta.url);
const out = new URL("../packages/core/src/design-text.ts", import.meta.url);

// The faces, weights and sizes OpenedBox sets the title in: containerTitle
// in packages/core/src/design.ts, whose test holds the table to them.
const styles = {
  title: '700 15px "Hanken Grotesk"',
  monoTitle: '500 14px "JetBrains Mono"',
  meta: '400 12px "Hanken Grotesk"',
};

// Printable Latin-1: what names and counts are written in. The layout counts
// anything else as wide as the widest of these, and at least as wide as the
// text is high.
const characters = [];
for (let code = 0x20; code <= 0xff; code++)
  if (code < 0x7f || code >= 0xa0) characters.push(String.fromCharCode(code));

// A page beside the fonts, so it may load them from disk.
const dir = mkdtempSync(join(tmpdir(), "codemap-text-widths-"));
const html = join(dir, "measure.html");
writeFileSync(html, `<!doctype html><link rel="stylesheet" href="${fonts.href}">`);
const browser = await chromium.launch({ args: ["--allow-file-access-from-files"] });
const page = await browser.newPage();
await page.goto(pathToFileURL(html).href);
// A string: this file is checked without the DOM types.
const widths = await page.evaluate(`(async () => {
  const styles = ${JSON.stringify(styles)};
  const characters = ${JSON.stringify(characters)};
  const context = document.createElement("canvas").getContext("2d");
  const table = {};
  for (const [name, style] of Object.entries(styles)) {
    const faces = await document.fonts.load(style, characters.join(""));
    // A face that did not load would be measured in a fallback font.
    if (faces.length === 0) throw new Error(style + " did not load");
    context.font = style;
    const row = {};
    for (const c of characters) row[c] = Math.round(context.measureText(c).width * 1000) / 1000;
    table[name] = row;
  }
  return table;
})()`);
await browser.close();
rmSync(dir, { recursive: true, force: true });

const body = Object.entries(widths)
  .map(([name, row]) => `  ${name}: ${JSON.stringify(row)},`)
  .join("\n");
writeFileSync(
  out,
  `// SPDX-License-Identifier: Apache-2.0

// Generated by scripts/text-widths.mjs; do not edit. How wide each printable
// Latin-1 character is, in CSS pixels, in the styles the title of an opened
// node's box is set in, measured with the fonts Codemap ships.

// The styles measured, as the canvas names them.
export const measuredWith = ${JSON.stringify(styles, null, 2)};

export const textWidths: Record<"title" | "monoTitle" | "meta", Record<string, number>> = {
${body}
};
`,
);
// Biome decides how the table is formatted, as it does every file.
execFileSync("pnpm", ["exec", "biome", "format", "--write", fileURLToPath(out)], {
  stdio: "ignore",
});
