// SPDX-License-Identifier: Apache-2.0

import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { chromium } from "@playwright/test";

const fonts = new URL("../packages/web/src/design/fonts/fonts.css", import.meta.url);
const out = new URL("../packages/core/src/design-text.ts", import.meta.url);

const styles = {
  title: '700 15px "Hanken Grotesk"',
  monoTitle: '500 14px "JetBrains Mono"',
  meta: '400 12px "Hanken Grotesk"',
};

// The layout counts other characters as wide as the widest.
function printableLatin1() {
  const printable = [];
  for (let code = 0x20; code <= 0xff; code++)
    if (code < 0x7f || code >= 0xa0) printable.push(String.fromCharCode(code));
  return printable;
}

// Beside the fonts, so the page can load them.
function pageBesideFonts() {
  const folder = mkdtempSync(join(tmpdir(), "codemap-text-widths-"));
  const file = join(folder, "measure.html");
  writeFileSync(file, `<!doctype html><link rel="stylesheet" href="${fonts.href}">`);
  return { dir: folder, html: file };
}

// A string: this file is checked without the DOM types.
/** @param {string[]} measured */
function measuring(measured) {
  return `(async () => {
  const styles = ${JSON.stringify(styles)};
  const characters = ${JSON.stringify(measured)};
  const context = document.createElement("canvas").getContext("2d");
  const table = {};
  for (const [name, style] of Object.entries(styles)) {
    const faces = await document.fonts.load(style, characters.join(""));
    // A face that did not load would be measured in a fallback font.
    if (faces.length === 0) throw new Error(style + " did not load");
    context.font = style;
    const row = {};
    for (const c of characters) row[c] = Math.round(context.measureText(c).width * 1000) / 1000;
    table[name] = row;
  }
  return table;
})()`;
}

// Biome formats the generated table, as it does every file.
/** @param {URL} file */
function formatWithBiome(file) {
  execFileSync("pnpm", ["exec", "biome", "format", "--write", fileURLToPath(file)], {
    stdio: "ignore",
  });
}

const characters = printableLatin1();
const { dir, html } = pageBesideFonts();
const browser = await chromium.launch({ args: ["--allow-file-access-from-files"] });
const page = await browser.newPage();
await page.goto(pathToFileURL(html).href);
const widths = await page.evaluate(measuring(characters));
await browser.close();
rmSync(dir, { recursive: true, force: true });

const body = Object.entries(widths)
  .map(([name, row]) => `  ${name}: ${JSON.stringify(row)},`)
  .join("\n");
writeFileSync(
  out,
  `// SPDX-License-Identifier: Apache-2.0

// Generated by scripts/text-widths.mjs; do not edit. How wide each printable
// Latin-1 character is, in CSS pixels, in the styles the title of an opened
// node's box is set in, measured with the fonts Codemap ships.

// The styles measured, as the canvas names them.
export const measuredWith = ${JSON.stringify(styles, null, 2)};

export const textWidths: Record<"title" | "monoTitle" | "meta", Record<string, number>> = {
${body}
};
`,
);
formatWithBiome(out);
